@AuthenticationService.Api_HostAddress = http://localhost:5048




POST {{AuthenticationService.Api_HostAddress}}/register
Content-Type: application/json

{
  "Email": "user@example.com",
  "Password": "YourPassword123",
  "ConfirmPassword": "YourPassword23"
}


### @AuthenticationService.Api_HostAddress = http://localhost:5048

### GET {{AuthenticationService.Api_HostAddress}}/weatherforecast/
### Accept: application/json
